import { v4 as uuid } from 'uuid';
import { IUserDto } from '../src/dtos/user.dto';

const data: IUserDto[] = [
  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Denis',
    lastname: 'Shevchenko',
    email: 'test@test.com',
    email_original: 'test@test.com',
    email_validation_outcome: null,
    role: 'administrator',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'SC-011',
    password: '$2a$10$aJ1aNsEU2PaKl7Kbrl06POcSRB/Yt2V3XEt48pbya2Ewisk.Bq4L.',
    schoox_id: 123123,
    schoox_above_id: null,
    is_deactivated: 0,  },
  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Summer',
    lastname: 'Elliott',
    email: 'summeraelliottaaa@gmail.com',
    email_original: 'summeraelliott@gmail.com',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'SC-011',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 982750856,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Brenda',
    lastname: 'McCoy',
    email: 'brendamccoy12aaa@aol.com',
    email_original: null,
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'SC-011',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 1384855924,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'montra',
    lastname: 'graham',
    email: 'montragraham3aaa@gmail.com',
    email_original: 'montragraham3@gmail.com',
    email_validation_outcome: 'safe',
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: '906545',
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'GA-073',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 1783623943,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Madison',
    lastname: 'Savage',
    email: 'msavage06aaa@icloud.com',
    email_original: 'msavage06@icloud.com',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 1720567407,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Madison',
    lastname: 'Williams',
    email: 'mewilliams9aaa@comcast.net',
    email_original: 'mewilliams9@comcast.net',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 902864224,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Maya',
    lastname: 'Melind',
    email: 'mayadaymelindaaa@gmail.com',
    email_original: 'mayadaymelind@gmail.com',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 734995208,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Larry',
    lastname: 'Lavigne',
    email: 'l5lavigne01aaa@gmail.com',
    email_original: 'l5lavigne01@gmail.com',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 666695884,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Emma',
    lastname: 'Nieman',
    email: 'emmalindsey5aaa@gmail.com',
    email_original: null,
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 146923449,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Devin',
    lastname: 'Dodson',
    email: 'devindodson5aaa@gmail.com',
    email_original: null,
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 10897864,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Ava',
    lastname: 'Lavigne',
    email: 'ava.lavigne0530aaa@gmail.com',
    email_original: 'ava.lavigne0530@gmail.com',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 670770260,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Ali',
    lastname: 'Ramer',
    email: 'aligovolsaaa@icloud.com',
    email_original: 'aligovols@icloud.com',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 739841924,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'AJ',
    lastname: 'Harris',
    email: 'ajharris2019aaa@gmail.com',
    email_original: 'ajharris2019@gmail.com',
    email_validation_outcome: null,
    role: 'shift_leader',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 151369111,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Rachel',
    lastname: 'Hillman',
    email: '2021rchaaa@gmail.com',
    email_original: '2021rch@gmail.com',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 1129316592,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Nicolas',
    lastname: 'Shaner',
    email: 'shanenic000aaa@icloud.com',
    email_original: 'shanenic000@icloud.com',
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 1969561909,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Chloe',
    lastname: 'Lyons',
    email: 'raffiecomputeraaa@gmail.com',
    email_original: null,
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 1240778750,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Payton',
    lastname: 'Harmon',
    email: 'paytonharmon21aaa@gmail.com',
    email_original: null,
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 164886141,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Nicole',
    lastname: 'Ward',
    email: 'nward8aaa@vols.utk.edu',
    email_original: null,
    email_validation_outcome: null,
    role: 'assistant_manager',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 1896405403,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Jennifer',
    lastname: 'Douglas',
    email: 'Jenniferleighdouglasaaa@gmail.com',
    email_original: null,
    email_validation_outcome: null,
    role: 'crew_member',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 1920803595,
    schoox_above_id: null,
    is_deactivated: 0,
  },

  {
    uuid: uuid(),
    created: new Date(),
    completed: null,
    changed: null,
    in_draft: 0,
    langcode: 'en',
    firstname: 'Gabriel',
    lastname: 'Pless',
    email: 'gabriel.pless94aaa@gmail.com',
    email_original: null,
    email_validation_outcome: null,
    role: 'shift_leader',
    employment_status: 'Hourly',
    roles: 'employee,hourly_worker',
    decentralized_cafes: null,
    is_head_of_decentralized_cafes: 0,
    cafe_number: 'TN-021',
    password: '$2b$10$bq8mnzIoywyiTPL9h/poReCefULaDh/8SkutV45Ge8Edbv0oqq302',
    schoox_id: 675970984,
    schoox_above_id: null,
    is_deactivated: 0,
  },
];

const config = {
  modelName: 'User',
  data,
};

export { config };
