CREATE TABLE `users` (
  `uuid` varchar(255) NOT NULL,
  `schoox_id` bigint DEFAULT NULL,
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email_original` varchar(255) DEFAULT NULL,
  `email_validation_outcome` varchar(45) DEFAULT NULL,
  `langcode` varchar(45) NOT NULL,
  `role` varchar(45) DEFAULT NULL,
  `roles` varchar(255) DEFAULT NULL,
  `decentralized_cafes` varchar(255) DEFAULT NULL,
  `is_head_of_decentralized_cafes` tinyint DEFAULT NULL,
  `cafe_number` mediumtext,
  `schoox_above_id` bigint DEFAULT NULL,
  `created` timestamp(6) NULL DEFAULT NULL,
  `completed` timestamp(6) NULL DEFAULT NULL,
  `changed` timestamp(6) NULL DEFAULT NULL,
  `in_draft` tinyint DEFAULT '0',
  `is_deactivated` tinyint DEFAULT '0',
  `employment_status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `uuid_UNIQUE` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
